# Generated by Django 4.1 on 2024-01-25 12:18

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('user_type', models.PositiveSmallIntegerField(choices=[(1, '系统管理员'), (2, '普通用户'), (3, '商户管理员')], default=2, verbose_name='用户类型')),
                ('telephone', models.CharField(max_length=11, verbose_name='手机号码')),
                ('name', models.CharField(max_length=12, verbose_name='用户姓名')),
                ('sid', models.CharField(max_length=24, verbose_name='身份证')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '系统用户',
                'verbose_name_plural': '系统用户',
                'db_table': 'User',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='MerchantStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_style_name', models.CharField(max_length=120, unique=True, verbose_name='商户类型名称')),
            ],
            options={
                'verbose_name': '商户类型',
                'verbose_name_plural': '商户类型',
                'db_table': 'merchant_style',
            },
        ),
        migrations.CreateModel(
            name='stra_Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_title', models.CharField(max_length=255, null=True, verbose_name='信号描述')),
                ('symbol', models.CharField(max_length=70, null=True, verbose_name='名称')),
                ('scode', models.CharField(max_length=30, null=True, verbose_name='代码')),
                ('contractType', models.IntegerField(blank=True, choices=[(1, '商品期货'), (2, '股票'), (3, '虚拟货币')], null=True, verbose_name='交易合约类型')),
                ('price', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='价格')),
                ('action', models.CharField(max_length=100, verbose_name='交易方向')),
                ('status', models.BooleanField(blank=True, default=False, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='触发时间')),
            ],
            options={
                'verbose_name': '交易信号提醒',
                'verbose_name_plural': '交易信号提醒',
                'db_table': 'stra_Alert',
            },
        ),
        migrations.CreateModel(
            name='stra_Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange', models.CharField(max_length=50, verbose_name='交易所')),
                ('symbol', models.CharField(max_length=50, verbose_name='交易对')),
                ('type', models.CharField(max_length=50, verbose_name='订单类型')),
                ('side', models.CharField(max_length=50, verbose_name='买卖方向')),
                ('amount', models.DecimalField(decimal_places=8, max_digits=18, verbose_name='交易数量')),
                ('price', models.DecimalField(decimal_places=8, max_digits=18, verbose_name='价格')),
                ('filled', models.DecimalField(decimal_places=8, max_digits=18, verbose_name='已成交数量')),
                ('remaining', models.DecimalField(decimal_places=8, max_digits=18, verbose_name='剩余数量')),
                ('status', models.CharField(max_length=50, verbose_name='订单状态')),
                ('timestamp', models.DateTimeField(verbose_name='订单时间')),
            ],
            options={
                'verbose_name': '交易订单',
                'verbose_name_plural': '交易订单',
                'db_table': 'stra_order',
            },
        ),
        migrations.CreateModel(
            name='TimeCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='应用周期名称')),
            ],
            options={
                'db_table': 'TimeCycle',
            },
        ),
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategy_name', models.CharField(max_length=120, unique=True, verbose_name='策略名称')),
                ('strategy_desc', models.TextField(blank=True, max_length=255, verbose_name='策略描述')),
                ('status', models.BooleanField(default=True, verbose_name='策略状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('stra_creater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='策略创建者')),
                ('strategy_time_cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alert.timecycle', verbose_name='策略时间周期')),
            ],
            options={
                'verbose_name': '交易策略',
                'verbose_name_plural': '交易策略',
                'db_table': 'strategy',
                'ordering': ('-update_time',),
            },
        ),
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_name', models.CharField(max_length=120, unique=True, verbose_name='商户名称')),
                ('merchant_address', models.TextField(blank=True, max_length=255, verbose_name='商户地址')),
                ('merchant_phone', models.CharField(max_length=11, unique=True, verbose_name='商户联系电话')),
                ('merchant_email', models.EmailField(max_length=120, unique=True, verbose_name='商户联系邮箱')),
                ('merchant_web', models.URLField(max_length=120, unique=True, verbose_name='商户网站')),
                ('merchant_id', models.CharField(max_length=120, unique=True, verbose_name='商户ID编号')),
                ('merchant_status', models.BooleanField(default=True, verbose_name='商户状态')),
                ('merchant_create_time', models.DateTimeField(auto_now_add=True, verbose_name='商户创建时间')),
                ('merchant_update_time', models.DateTimeField(auto_now=True, verbose_name='商户更新时间')),
                ('merchant_style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alert.merchantstyle', verbose_name='商户类型')),
                ('merchant_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='商户管理员')),
            ],
            options={
                'verbose_name': '商户基本信息',
                'verbose_name_plural': '商户基本信息',
                'db_table': 'merchant',
                'ordering': ('-merchant_update_time',),
            },
        ),
    ]
