# Generated by Django 4.1 on 2024-01-22 16:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='stra_Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_title', models.CharField(max_length=255, null=True, verbose_name='信号描述')),
                ('symbol', models.CharField(max_length=70, null=True, verbose_name='名称')),
                ('scode', models.CharField(max_length=30, null=True, verbose_name='代码')),
                ('contractType', models.IntegerField(blank=True, choices=[(1, '商品期货'), (2, '股票'), (3, '虚拟货币')], null=True, verbose_name='交易合约类型')),
                ('price', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='价格')),
                ('action', models.CharField(max_length=100, verbose_name='交易方向')),
                ('status', models.BooleanField(blank=True, default=False, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='触发时间')),
            ],
            options={
                'verbose_name': '交易信号提醒',
                'verbose_name_plural': '交易信号提醒',
                'db_table': 'stra_Alert',
            },
        ),
        migrations.CreateModel(
            name='stra_Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange', models.CharField(max_length=50, verbose_name='交易所')),
                ('symbol', models.CharField(max_length=50, verbose_name='交易对')),
                ('type', models.CharField(max_length=50, verbose_name='订单类型')),
                ('side', models.CharField(max_length=50, verbose_name='买卖方向')),
                ('amount', models.DecimalField(decimal_places=8, max_digits=18, verbose_name='交易数量')),
                ('price', models.DecimalField(decimal_places=8, max_digits=18, verbose_name='价格')),
                ('filled', models.DecimalField(decimal_places=8, max_digits=18, verbose_name='已成交数量')),
                ('remaining', models.DecimalField(decimal_places=8, max_digits=18, verbose_name='剩余数量')),
                ('status', models.CharField(max_length=50, verbose_name='订单状态')),
                ('timestamp', models.DateTimeField(verbose_name='订单时间')),
            ],
            options={
                'verbose_name': '交易订单',
                'verbose_name_plural': '交易订单',
                'db_table': 'stra_order',
            },
        ),
        migrations.CreateModel(
            name='TimeCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='应用周期名称')),
            ],
            options={
                'db_table': 'TimeCycle',
            },
        ),
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategy_name', models.CharField(max_length=120, unique=True, verbose_name='策略名称')),
                ('strategy_desc', models.TextField(blank=True, max_length=255, verbose_name='策略描述')),
                ('status', models.BooleanField(default=True, verbose_name='策略状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('stra_creater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='策略创建者')),
                ('strategy_time_cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alert.timecycle', verbose_name='策略时间周期')),
            ],
            options={
                'verbose_name': '交易策略',
                'verbose_name_plural': '交易策略',
                'db_table': 'strategy',
                'ordering': ('-update_time',),
            },
        ),
    ]
