# Generated by Django 4.1 on 2024-01-24 16:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('alert', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MerchantStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_style_name', models.CharField(max_length=120, unique=True, verbose_name='商户类型名称')),
            ],
            options={
                'verbose_name': '商户类型',
                'verbose_name_plural': '商户类型',
                'db_table': 'merchant_style',
            },
        ),
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_name', models.CharField(max_length=120, unique=True, verbose_name='商户名称')),
                ('merchant_address', models.TextField(blank=True, max_length=255, verbose_name='商户地址')),
                ('merchant_phone', models.CharField(max_length=11, unique=True, verbose_name='商户联系电话')),
                ('merchant_email', models.EmailField(max_length=120, unique=True, verbose_name='商户联系邮箱')),
                ('merchant_web', models.URLField(max_length=120, unique=True, verbose_name='商户网站')),
                ('merchant_id', models.CharField(max_length=120, unique=True, verbose_name='商户ID编号')),
                ('merchant_status', models.BooleanField(default=True, verbose_name='商户状态')),
                ('merchant_create_time', models.DateTimeField(auto_now_add=True, verbose_name='商户创建时间')),
                ('merchant_update_time', models.DateTimeField(auto_now=True, verbose_name='商户更新时间')),
                ('merchant_style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alert.merchantstyle', verbose_name='商户类型')),
                ('merchant_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='商户管理员')),
            ],
            options={
                'verbose_name': '商户基本信息',
                'verbose_name_plural': '商户基本信息',
                'db_table': 'merchant',
                'ordering': ('-merchant_update_time',),
            },
        ),
    ]
