# Generated by Django 4.1 on 2024-08-11 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0002_stra_alert_time_circle_alter_stra_alert_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stra_order',
            name='order_id',
            field=models.CharField(default=1, max_length=100, unique=True, verbose_name='订单ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stra_order',
            name='position_action',
            field=models.CharField(choices=[(1, '开仓'), (0, '平仓')], default=0, max_length=50, verbose_name='开仓/平仓'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stra_order',
            name='side',
            field=models.CharField(choices=[('buy', '买入'), ('sell', '卖出')], max_length=50, verbose_name='买卖方向'),
        ),
        migrations.AlterField(
            model_name='stra_order',
            name='status',
            field=models.CharField(choices=[('pending', '待处理'), ('partially_filled', '部分成交'), ('filled', '完全成交'), ('cancelled', '已取消'), ('failed', '失败')], max_length=50, verbose_name='订单状态'),
        ),
    ]
