# Generated by Django 4.1 on 2024-08-11 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0003_stra_order_order_id_stra_order_position_action_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stra_order',
            name='type',
            field=models.CharField(choices=[('limit', '限价单'), ('market', '市价单'), ('stop_loss', '止损单')], max_length=50, verbose_name='订单类型'),
        ),
    ]
