# Generated by Django 4.1 on 2024-08-14 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0004_alter_stra_order_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='stra_alert',
            name='strategy_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='alert.strategy', verbose_name='策略ID'),
        ),
    ]
