# Generated by Django 4.1 on 2024-08-14 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0005_stra_alert_strategy_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategy',
            name='strategy_desc',
            field=models.TextField(blank=True, verbose_name='策略描述'),
        ),
    ]
