# Generated by Django 4.1 on 2025-02-26 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0006_alter_strategy_strategy_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='交易所名称')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='交易所代码')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('api_url', models.CharField(max_length=200, verbose_name='API地址')),
                ('test_api_url', models.CharField(blank=True, max_length=200, verbose_name='测试API地址')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '交易所',
                'verbose_name_plural': '交易所',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='ContractCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20, verbose_name='交易对象符号')),
                ('name', models.CharField(max_length=50, verbose_name='交易对象名称')),
                ('description', models.CharField(blank=True, max_length=100, verbose_name='描述')),
                ('product_type', models.CharField(choices=[('spot', '现货'), ('perpetual', '永续合约')], default='perpetual', max_length=20, verbose_name='产品类型')),
                ('min_size', models.DecimalField(decimal_places=8, max_digits=18, verbose_name='最小下单数量')),
                ('size_increment', models.DecimalField(decimal_places=8, max_digits=18, verbose_name='数量增量')),
                ('price_precision', models.IntegerField(verbose_name='价格精度')),
                ('size_precision', models.IntegerField(verbose_name='数量精度')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='alert.exchange', verbose_name='交易所')),
            ],
            options={
                'verbose_name': '交易对',
                'verbose_name_plural': '交易对',
                'ordering': ['exchange', 'symbol'],
                'unique_together': {('exchange', 'symbol')},
            },
        ),
    ]
