# Generated by Django 4.1 on 2025-02-27 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0007_exchange_contractcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(help_text='订单ID', max_length=100, unique=True)),
                ('cloid', models.CharField(help_text='客户端订单ID', max_length=100, null=True)),
                ('symbol', models.CharField(help_text='交易对', max_length=20)),
                ('side', models.CharField(help_text='买卖方向', max_length=10)),
                ('order_type', models.CharField(help_text='订单类型', max_length=20)),
                ('price', models.DecimalField(decimal_places=8, help_text='价格', max_digits=20)),
                ('quantity', models.DecimalField(decimal_places=8, help_text='数量', max_digits=20)),
                ('position_type', models.CharField(help_text='持仓类型(open/close)', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', '等待中'), ('SUBMITTED', '已提交'), ('FILLED', '已成交'), ('PARTIALLY_FILLED', '部分成交'), ('CANCELLED', '已撤销'), ('FAILED', '失败')], default='PENDING', help_text='订单状态', max_length=20)),
                ('filled_quantity', models.DecimalField(decimal_places=8, default=0, help_text='已成交数量', max_digits=20)),
                ('retry_count', models.IntegerField(default=0, help_text='重试次数')),
                ('last_retry_time', models.DateTimeField(help_text='最后重试时间', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '订单记录',
                'verbose_name_plural': '订单记录',
                'db_table': 'order_record',
            },
        ),
        migrations.AddIndex(
            model_name='orderrecord',
            index=models.Index(fields=['symbol', 'created_at'], name='order_recor_symbol_4d9c23_idx'),
        ),
        migrations.AddIndex(
            model_name='orderrecord',
            index=models.Index(fields=['status', 'created_at'], name='order_recor_status_b702fa_idx'),
        ),
    ]
