# Generated by Django 4.1 on 2025-02-27 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0008_orderrecord_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractcode',
            name='default_quantity',
            field=models.DecimalField(decimal_places=8, default=1.0, max_digits=18, verbose_name='默认下单数量'),
        ),
    ]
