# Generated by Django 4.1 on 2024-01-22 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0009_timecircle_alter_strategy_strategy_time_cycle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategy',
            name='strategy_time_cycle',
            field=models.CharField(choices=[('1m', '1分钟'), ('5m', '5分钟'), ('15m', '15分钟'), ('30m', '30分钟'), ('1h', '1小时'), ('2h', '2小时'), ('4h', '4小时'), ('6h', '6小时'), ('12h', '12小时'), ('1d', '1天'), ('1w', '1周')], max_length=50, verbose_name='策略应用时间周期'),
        ),
        migrations.DeleteModel(
            name='TimeCircle',
        ),
    ]
