# Generated by Django 4.1 on 2025-02-27 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0009_contractcode_default_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stra_order',
            name='status',
            field=models.CharField(choices=[('PENDING', '待处理'), ('SUBMITTED', '已委托'), ('FILLED', '已成交'), ('CANCELLED', '已撤销'), ('FAILED', '失败')], default='PENDING', max_length=50, verbose_name='订单状态'),
        ),
    ]
