# Generated by Django 4.1 on 2025-02-27 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0010_alter_stra_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exchange',
            name='api_url',
        ),
        migrations.RemoveField(
            model_name='exchange',
            name='test_api_url',
        ),
    ]
