# Generated by Django 4.1 on 2024-01-22 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0010_alter_strategy_strategy_time_cycle_delete_timecircle'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='应用周期名称')),
            ],
            options={
                'db_table': 'TimeCycle',
            },
        ),
        migrations.AlterField(
            model_name='strategy',
            name='strategy_time_cycle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alert.timecycle', verbose_name='策略时间周期'),
        ),
    ]
