# Generated by Django 4.1 on 2025-03-10 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0011_remove_exchange_api_url_remove_exchange_test_api_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractcode',
            name='stop_loss_percentage',
            field=models.DecimalField(decimal_places=2, default=10.0, help_text='止损百分比，默认为10%', max_digits=5, verbose_name='止损百分比'),
        ),
    ]
