# Generated by Django 4.1 on 2025-03-10 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0014_alter_contractcode_default_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderrecord',
            name='is_stop_loss',
            field=models.BooleanField(default=False, help_text='是否为止损单'),
        ),
    ]
