# Generated by Django 4.1 on 2025-03-11 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0015_orderrecord_is_stop_loss'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractcode',
            name='stop_loss_slippage',
            field=models.DecimalField(decimal_places=2, default=0.5, help_text='止损单滑点百分比，默认为0.5%', max_digits=4, verbose_name='止损单滑点'),
        ),
        migrations.AlterField(
            model_name='contractcode',
            name='stop_loss_percentage',
            field=models.DecimalField(decimal_places=1, default=8.0, help_text='止损百分比，默认为8%', max_digits=5, verbose_name='止损百分比'),
        ),
    ]
