# Generated by Django 5.1.7 on 2025-03-13 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0017_remove_orderrecord_order_recor_symbol_4d9c23_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderrecord',
            name='fee',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='手续费'),
        ),
        migrations.AddField(
            model_name='orderrecord',
            name='filled_time',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='成交时间戳'),
        ),
        migrations.AddField(
            model_name='orderrecord',
            name='oid',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='渠道订单ID'),
        ),
        migrations.AddField(
            model_name='orderrecord',
            name='order_type',
            field=models.CharField(choices=[('OPEN', '开仓单'), ('CLOSE', '平仓单'), ('UNKNOWN', '未知类型')], default='UNKNOWN', max_length=20, verbose_name='订单类型'),
        ),
    ]
