# Generated by Django 5.1.7 on 2025-03-14 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0018_orderrecord_fee_orderrecord_filled_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrecord',
            name='avg_price',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=18, null=True, verbose_name='成交均价'),
        ),
        migrations.AlterField(
            model_name='orderrecord',
            name='fee',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='订单成交的手续费', max_digits=18, null=True, verbose_name='手续费'),
        ),
        migrations.AlterField(
            model_name='orderrecord',
            name='filled_quantity',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=18, null=True, verbose_name='已成交数量'),
        ),
        migrations.AlterField(
            model_name='orderrecord',
            name='filled_time',
            field=models.BigIntegerField(blank=True, help_text='成交时间戳（毫秒）', null=True, verbose_name='成交时间戳'),
        ),
        migrations.AlterField(
            model_name='orderrecord',
            name='oid',
            field=models.CharField(blank=True, help_text='交易所平台的原始订单ID', max_length=50, null=True, verbose_name='渠道订单ID'),
        ),
        migrations.AlterField(
            model_name='orderrecord',
            name='order_type',
            field=models.CharField(choices=[('OPEN', '开仓单'), ('CLOSE', '平仓单')], default='UNKNOWN', help_text='订单类型：开仓单，平仓单', max_length=20, verbose_name='订单类型'),
        ),
        migrations.AlterField(
            model_name='orderrecord',
            name='quantity',
            field=models.DecimalField(decimal_places=5, max_digits=18, verbose_name='数量'),
        ),
    ]
