# Generated by Django 5.1.7 on 2025-03-18 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0020_alter_stra_alert_price_precision'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderrecord',
            name='filled_price',
            field=models.DecimalField(blank=True, decimal_places=5, help_text='订单实际成交价格，可能与下单价格不同', max_digits=18, null=True, verbose_name='成交价格'),
        ),
        migrations.AlterField(
            model_name='orderrecord',
            name='filled_quantity',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=18, verbose_name='已成交数量'),
        ),
        migrations.AlterField(
            model_name='orderrecord',
            name='filled_time',
            field=models.DateTimeField(blank=True, help_text='订单成交时间', null=True, verbose_name='成交时间'),
        ),
        migrations.AlterField(
            model_name='orderrecord',
            name='order_id',
            field=models.CharField(max_length=50, unique=True, verbose_name='订单ID'),
        ),
        migrations.AlterField(
            model_name='orderrecord',
            name='order_type',
            field=models.CharField(choices=[('OPEN', '开仓单'), ('CLOSE', '平仓单'), ('UNKNOWN', '未知')], default='UNKNOWN', help_text='订单类型：开仓单，平仓单', max_length=20, verbose_name='订单类型'),
        ),
        migrations.AlterField(
            model_name='orderrecord',
            name='price',
            field=models.DecimalField(decimal_places=5, max_digits=18, verbose_name='下单价格'),
        ),
        migrations.AlterField(
            model_name='stra_alert',
            name='price',
            field=models.DecimalField(decimal_places=5, max_digits=20, verbose_name='价格'),
        ),
    ]
