# Generated by Django 5.1.7 on 2025-03-18 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0022_alter_orderrecord_filled_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderrecord',
            old_name='oid',
            new_name='cloid',
        ),
    ]
