# Generated by Django 5.1.7 on 2025-03-19 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0023_rename_oid_orderrecord_cloid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='stra_Order',
        ),
    ]
