# Generated by Django 5.1.7 on 2025-03-20 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0024_remove_stra_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stra_alert',
            old_name='strategy_id',
            new_name='strategy',
        ),
    ]
